version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.2-20220317
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      # - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      # - SE_NODE_MAX_SESSIONS=10
      # - SE_NODE_MAX_INSTANCES=10
      # - SE_SESSION_TIMEOUT=10
 
  selenium-hub:
    image: selenium/hub:4.1.2-20220317
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=10